### ISSUE TITLE
Note20 Ultra

### ISSUE THREAD

**Issue by brericha** [brericha/S20-Refresh-Rate#12]
Hello new Note20 owners!

I would like to see if Samsung changed the way that changing between 60Hz and 120Hz works. As I am not going to be purchasing a Note20 Ultra for myself, I would appreciate it if those who did could give the app a shot for me. 

[Download and install version 0.5.0](https://github.com/Made-With-Fingertips/Dynamic-Display/releases/tag/v0.5.0) and follow the [instructions in the readme](https://github.com/Made-With-Fingertips/Dynamic-Display#installation) to grant the WRITE_SECURE_SETTINGS permission. The app will warn you about your device being unsupported, just dismiss it and try it out.

If you do test, please reply with what version of the phone you have, Snapdragon or Exynos.

Thank you!

**Comment by ShakeBake** [comment]
Hi. Thanks for the app. I've installed it on my note 20 ultra exynos version and it works well. The first couple of times it wouldn't swap from 60 back to 120. But a restart fixed those issues. 

I'm using this in conjunction with bixby routines to swap resolution as well.

Only issue I've found is that the youtube pop out window doesn't work. Just stops playing until i go back in and the resolution swaps again. There is also the issue of a stutter/freeze when changing resolution through routines. Though these are likely more to do with the bixby resolution swap than your app. 

Splitscreen and hovering apps work fine.

**Comment by ShakeBake** [comment]
Also. Not sure if it makes a difference or not. But the phonesettings say the frame rate is set to 'high' rather than adaptive. Not sure if this is forcing 120hz all the time or not.
![Screenshot_20200820-110117_Settings](https://user-images.githubusercontent.com/29230146/90756625-845f3e80-e2d4-11ea-9805-37f0a20bc253.jpg)

**Comment by brericha** [comment]
I would think that it would be running at 120Hz all the time when Dynamic Display sets the rate, as it tells the system to use a minimum of 60/96/120Hz based on what option is selected.
