### ISSUE TITLE
96 Hz is not working

### ISSUE THREAD

**Issue by ecast040** [brericha/S20-Refresh-Rate#9]
It doesn't matter if I set it from the toggle in quick settings or if I set the preference from the app for my web browser, I cannot enable 96 Hz from the app. I tried looking at the source code myself and I can't seem to find the root cause of this. I have the latest android update from samsung, need some help troubleshooting what's causing this. I've given access to the app and I can confirm it works for 120hz and 60 hz but trying to change to 96 Hz results in it staying at 120 hz.

**Comment by brericha** [comment]
Does this happen just with the web browser, or would it do the same thing if you set another app to 120 and then change it to 96?

**Comment by ecast040** [comment]
This happens with web browsers as far as I can tell since I have no way to verify frame rates on other apps. Using Chrome and brave browser with ufo test

**Comment by ecast040** [comment]
Newest 0.5 version still doesn't seem to enable 96hz in apps. Not sure if I'm missing something. Will download the latest source and see if I can debug what's going on.

**Comment by brericha** [comment]
I've been trying to figure out what needs to be set to get 96Hz to work with a separate app, but so far no dice. There is another method that I've seen used by [this app](https://github.com/SatySatsZB/S20RefreshRateControl), but as I am targeting a more recent version of Android, it won't work with Dynamic Display as it is currently designed. I've toyed with the idea of a rewrite where I _might_ be able to incorporate this method.

**Comment by ecast040** [comment]
I was considering doing just that because I've seen at least 2 applications doing it that way. I also heard some people got it working with Tasker but I haven't done too much investigation on that quite yet.

Ideally you'd just fork that project, add your background service to detect app changes and then run the relevant command. 

Oh BTW, we should also add 48 hz mode cause some apps and games won't render above 30 fps for some added battery life savings. 

I'm honestly down to helping you do the rewrite to get this working. I will say this project has taught me a lot,  haven't done android projects in years.

**Comment by brericha** [comment]
I played around with adb shell some more and found that calling `settings put system peak_refresh_rate 96.0` works. Unfortunately, non-system apps are not allowed to write to Settings.System via the Android API. 60Hz and 120Hz work through writing to Settings.Secure, which is what the current adb permissions command is for.

I believe that it would be possible to achieve the 96Hz command with root. I'd need help testing that as my S20 is not rooted and I am not going to root it.

A possibility is to make two apps, one that just does 60 and 120 that doesn't require root and will need the adb permissions command, and one that uses root for 60, 96, and 120 which would not need the adb permissions command as all three should work through shell commands.
